# Generated by Django 5.0.6 on 2025-09-24 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_category_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
